twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: ['*.twig']
    form_themes: ['bootstrap_5_layout.html.twig'] #style par defaut au formulaire

    globals:
        # ga_tracking: 'UA-XXXX'
        ORDER_CONFIRMATION: 'ORDER_CONFIRMATION'

when@test:
    twig:
        strict_variables: true
