# App\Entity\User:
#         properties:
#                 password:
#                         - NotNull: ~
#                         - NotBlank: ~
#                         - Type:
#                                   type: string
#                                   message: The value {{ value }} is not a valid {{ type }}.
#                         - Length:
#                                   max: 255
#                                   maxMessage: "field: password  cannot be longer than {{ limit }} characters"

#                 name:
#                         - NotNull: ~
#                         - NotBlank: ~
#                         - Type:
#                                   type: string
#                                   message: The value {{ value }} is not a valid {{ type }}.
#                         - Length:
#                                   min: 2
#                                   max: 20
#                                   minMessage: "field: nom must be at least {{ limit }} characters long"
#                                   maxMessage: "field: nom  cannot be longer than {{ limit }} characters"

#                 first_name:
#                         - NotNull: ~
#                         - NotBlank: ~
#                         - Type:
#                                   type: string
#                                   message: The value {{ value }} is not a valid {{ type }}.
#                         - Length:
#                                   min: 2
#                                   max: 20
#                                   minMessage: "field: prenom must be at least {{ limit }} characters long"
#                                   maxMessage: "field: prenom  cannot be longer than {{ limit }} characters"

#                 email:
#                         - NotNull: ~
#                         - NotBlank: ~
#                         - Type:
#                                   type: string
#                                   message: The value {{ value }} is not a valid {{ type }}.
#                         - Length:
#                                   max: 180
#                                   maxMessage: "field: email  cannot be longer than {{ limit }} characters"
#                 ville:
#                         - NotNull: ~
#                         - NotBlank: ~
#                         - Type:
#                                   type: string
#                                   message: The value {{ value }} is not a valid {{ type }}.
#                         - Length:
#                                   max: 20
#                                   maxMessage: "field: ville  cannot be longer than {{ limit }} characters"
#                 roles:
#                         - NotNull: ~
#                         - NotBlank: ~
#                         - Type:
#                                   type: string
#                                   message: The value {{ value }} is not a valid {{ type }}.

App\Entity\Categorie:
        properties:
                name:
                        - NotNull: ~
                        - NotBlank: ~
                        - Type:
                                type: string
                                message: The value {{ value }} is not a valid {{ type }}
                        - Length:
                                min: 1
                                max: 45
                                minMessage: "Field 'Nom' must be at least {{ limit }} chartchter long"
                                maxMessage: "Field 'Nom' must be at least {{ limit }} chartchter"               

App\Entity\Commande:
        date:
                        - Type:
                                  type: \DateTimeInterface
                                  message: The value {{ value }} is not a valid {{ type }}.
 
App\Entity\Panier:
        properties:

App\Entity\Produit:
        App\Entity\Produit:
        properties:
                name:
                        - NotNull: ~
                        - NotBlank: ~
                        - Type:
                                  type: string
                                  message: The value {{ value }} is not a valid {{ type }}.
                        - Length:
                                  max: 100
                                  maxMessage: "field: titre  cannot be longer than {{ limit }} characters"

                description:
                        - NotNull: ~
                        - NotBlank: ~
                        - Type:
                                  type: string
                                  message: The value {{ value }} is not a valid {{ type }}.
                        - Length:
                                  min: 2
                                  minMessage: "field: description must be at least {{ limit }} characters long"

                img:
                        - NotNull: ~
                        - NotBlank: ~
                        - Type:
                                  type: string
                                  message: The value {{ value }} is not a valid {{ type }}.
                        - Length:
                                  max: 300
                                  maxMessage: "field: photo must be at most {{ limit }} characters long"

                prix:
                        - NotNull: ~
                        - NotBlank: ~
                        - Type:
                                  type: integer
                                  message: The value {{ value }} is not a valid {{ type }}.