controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET|POST

#Page statiques

app_legale:
    path: /mentions
    controller: App\Controller\StaticController::mentionsLegales
    methods: GET

app_cookies:
    path: /cookies
    controller: App\Controller\StaticController::politiqueCookies
    methods: GET
