controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Les routes de l'application

# ----------------- HomeController ----------------------

# Appelle la page d'accueil
app_home:
    path: /
    controllers: App\Controller\HomeController # par default : index
    methods: GET|POST