controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET|POST

# app_login:
#     path: /login
#     controller: App\Controller\LoginController::connexion
#     methods: GET|POST

#Page statiques
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

# app_inscription:
#     path: /inscription
#     controller: App\Controller\SController::inscription
#     methods: GET

app_politiqueconfidentialite:
    path: /polititiqueconfidentialite
    controller: App\Controller\StaticController::politiqueConfidentialite
    methods: GET

app_cgv:
    path: /cgv
    controller: App\Controller\StaticController::cgv
    methods: GET

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

# app_admin:
#     path: /admin
#     controller: App\Controller\Admin\Dashboard::index

app_admin_user_management:
    path: /easyadmin/user
    controller: App\Controller\AdminController::userManagement

# app_user:
#     path: user/profil
#     controller: App\Controller\UserController::dashboard

app_nos_realisations:
    path: /realisations
    controller: App\Controller\NosRealisationsController::realisation
    methods: GET

app_profil:
    path: /profil
    controller: App\Controller\ProfilController::profil
    methods: GET

app_contact:
    path: /contact
    controller: App\Controller\ContactController::contact
    methods: [GET, POST]

app_produit:
    path: /admin/produit
    controller: App\Controller\ProduitController::index
    methods: GET

app_add_produit:
    path: /admin/produit/ajout
    controller: App\Controller\ProduitController::add
    methods: GET

app_edit_produit:
    path: /admin/produit/edition/{id}
    controller: App\Controller\ProduitController::edit
    methods: GET

app_supp_produit:
    path: /admin/produit/supp/{id}
    controller: App\Controller\ProduitController::delete
    methods: GET

app_categorie:
    path: /admin/categorie
    controller: App\Controller\CategorieController::index
    methods: GET

app_add_categorie:
    path: /admin/categorie/ajout
    controller: App\Controller\categorieController::add
    methods: GET, POST

app_edit_categorie:
    path: /admin/categorie/edition/{id}
    controller: App\Controller\categorieController::edit
    methods: GET

app_supp_categorie:
    path: /admin/categorie/supp/{id}
    controller: App\Controller\categorieController::delete
    methods: GET

app_users:
    path: /admin/user
    controller: App\Controller\admin\UserController::index
    methods: GET

app_users_commande:
    path: /admin/users_commande/{id}
    controller: App\Controller\admin\UserController::users_commande
    methods: GET
    
app_add_users:
    path: /admin/user/ajout
    controller: App\Controller\admin\UserController::add
    methods: GET

app_edit_users:
    path: /admin/user/edition_user/{id}
    controller: App\Controller\admin\UserController::edit_user
    methods: GET

app_supp_users:
    path: /admin/user/supp_user/{id}
    controller: App\Controller\admin\UserController::delete
    methods: GET


app_ecommerce:
    path: /ecommerce
    controller: App\Controller\ECommerceController::ecommerce
    methods: GET

app_vitrine:
    path: /vitrine
    controller: App\Controller\VitrineController::vitrine
    methods: GET

app_sur_mesure:
    path: /sur_mesure
    controller: App\Controller\SurMesureController::surMesure
    methods: GET

app_logo:
    path: /logo
    controller: App\Controller\LogoController::logo
    methods: GET

app_panier:
    path: /panier
    controller: App\Controller\PanierController::panier
    methods: GET

app_legale:
    path: /mentions
    controller: App\Controller\StaticController::mentionsLegales
    methods: GET

app_cookies:
    path: /cookies
    controller: App\Controller\StaticController::politiqueCookies
    methods: GET

app_logout:
    path: /logout
    methods: GET



app_stripe:
  path: /stripe
  controller: App\Controller\StripeController::index

app_stripe_charge:
  path: /stripe/create-charge
  controller: App\Controller\StripeController::createCharge
  methods: POST

app_stripe_success:
  path: /order/confirmation
  controller: App\Controller\StripeController::stripeSuccess

app_stripe_fail:
  path: /payment/failure
  controller: App\Controller\StripeController::paymentFailure

# reset_mdp:
app_forgot_password_request:
    path: /reset-password/request
    controller: App\Controller\ResetPasswordController::request
    methods: [GET, POST]

reset_password:
    path: /reset-password/{token}
    controller: App\Controller\ResetPasswordController::reset
    methods: [GET, POST]
