controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET|POST

# app_login:
#     path: /login
#     controller: App\Controller\LoginController::connexion
#     methods: GET|POST

#Page statiques

# app_inscription:
#     path: /inscription
#     controller: App\Controller\SController::inscription
#     methods: GET

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail

app_admin:
    path: /admin
    controller: App\Controller\AdminController::dashboard

app_admin_user_management:
    path: /admin/user
    controller: App\Controller\AdminController::userManagement

app_user:
    path: user/profile
    controller: App\Controller\UserController::dashboard

app_nos_realisations:
    path: /realisations
    controller: App\Controller\NosRealisationsController::realisation
    methods: GET

app_ecommerce:
    path: /ecommerce
    controller: App\Controller\ECommerceController::ecommerce
    methods: GET

app_vitrine:
    path: /vitrine
    controller: App\Controller\VitrineController::vitrine
    methods: GET

app_sur_mesure:
    path: /sur_mesure
    controller: App\Controller\SurMesureController::sur_mesure
    methods: GET

app_logo:
    path: /logo
    controller: App\Controller\LogoController::logo
    methods: GET

app_panier:
    path: /panier
    controller: App\Controller\PanierController::panier
    methods: GET

app_legale:
    path: /mentions
    controller: App\Controller\StaticController::mentionsLegales
    methods: GET

app_cookies:
    path: /cookies
    controller: App\Controller\StaticController::politiqueCookies
    methods: GET

app_logout:
    path: /logout
    methods: GET